let number = 10;
console.log("Initial value:", number); 
number += 5;
console.log("After += 5:", number); 
number -= 3;
console.log("After -= 3:", number); 
number *= 2;
console.log("After *= 2:", number); 
number /= 4;
console.log("After /= 4:", number); 
number %= 5;
console.log("After %= 5:", number); 